tap "jaxxstorm/tap"

# CLI tools
brew "awscli"
brew "azure-cli"
brew "bash"
brew "binutils"
brew "cdrdao"
brew "cloc"
brew "colima"
brew "consul"
brew "coreutils"
brew "direnv"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "jq"
brew "mas"
brew "maven"
brew "p7zip"
brew "pinentry-mac"
brew "pkgconf"
brew "reattach-to-user-namespace"
brew "rsync"
brew "ruby"
brew "rust"
brew "shfmt"
brew "steamguard-cli"
brew "telnet"
brew "terraform"
brew "tmux"
brew "transmission-cli"
brew "weechat"
brew "zsh"
brew "jaxxstorm/tap/aws-sso-creds"

# GUI apps
cask "1password"
cask "1password-cli"
cask "ghostty"
cask "alfred"
cask "brave-browser"
cask "claude"
cask "claude-code"
cask "crossover"
cask "deckset"
cask "discord"
cask "docker-desktop"
cask "dotnet-sdk"
cask "dropbox"
cask "font-fira-code"
cask "gimp"
cask "go-agent"
cask "google-chrome"
cask "google-drive"
cask "keybase"
cask "nordvpn"
cask "notable"
cask "obs"
cask "p4"
cask "p4v"
cask "postman"
cask "rar"
cask "slack"
cask "steam"
cask "telegram"
cask "unity-hub"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"

# Mac App Store
mas "1Password for Safari", id: 1569813296
mas "Final Cut Pro", id: 424389933
mas "Color Picker", id: 1545870783
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Windows App", id: 1295203466
